quarkus:
  log:
    category:
      "io.smallrye.jwt":
        level: DEBUG

mp:
  jwt:
    verify:
      publickey:
        location: jwt/publicKey.pem
      algorithm: RS256
    issuer: https://dompetly.lukmann.dev

smallrye:
  jwt:
    sign:
      key:
        location: jwt/privateKey.pem
      key-format: PEM
      algorithm: RS256
