quarkus:
  log:
    category:
      "io.smallrye.jwt":
        level: DEBUG

mp:
  jwt:
    verify:
      publickey:
        location: file:/etc/dompetly_api/jwt/publicKey.pem
      algorithm: RS256
    issuer: Dompetly App

smallrye:
  jwt:
    sign:
      key:
        location: file:/etc/dompetly_api/jwt/privateKey.pem
      key-format: PEM
      algorithm: RS256
