quarkus:
  profile: dev
  http:
    port: 8080
    auth:
      permission:
        authenticated:
          paths: /api/authenticated/*
          policy: authenticated
        public:
          paths: /api/auth/*
          policy: permit
  datasource:
    db-kind: postgresql
    username: ${JDBC_USER:dompetly_user}
    password: ${JDBC_PASSWORD:P@ssw0rd123}
    jdbc:
      url: ${JDBC_URL:jdbc:postgresql://127.0.0.1:5432/dompetly_db}
      enable-metrics: true
    metrics:
      enabled: true
  hibernate-orm:
    database:
      generation: none
    log:
      sql: false
  swagger-ui:
    enable: true
    always-include: true