quarkus:
  http:
    root-path: /api
    port: 8080
    auth:
      permission:
        authenticated:
          paths: /authenticated/*
          policy: authenticated
        public:
          paths: /auth/*
          policy: permit
  datasource:
    db-kind: postgresql
    username: ${JDBC_USER:dompetly_user}
    password: ${JDBC_PASSWORD:P@ssw0rd123}
    jdbc:
      url: ${JDBC_URL:jdbc:postgresql://127.0.0.1:5432/dompetly_db}
      enable-metrics: true
    metrics:
      enabled: true
  hibernate-orm:
    database:
      generation: none
    log:
      sql: false
  swagger-ui:
    enable: true
    always-include: true
    path: /api/q/swagger-ui
  smallrye-openapi:
    path: /api/q/openapi
    servers:
      - url: /api