quarkus:
  profile: dev
  http:
    port: 8080
    auth:
      permission:
        authenticated:
          paths: /api/authenticated/*
          policy: authenticated
        public:
          paths: /api/auth/*
          policy: permit
  datasource:
    db-kind: postgresql
    username: ${JDBC_USER:dompetly_user}
    password: ${JDBC_PASSWORD:P@ssw0rd123}
    jdbc:
      url: 'jdbc:postgresql://localhost:5432/dompetly_db'
      enable-metrics: true
    metrics:
      enabled: true
  hibernate-orm:
    database:
      generation: none
    log:
      sql: false
  smallrye-openapi:
    enable: true
    info-title: "Dompetly API"
    info-version: 1.0.0
    info-description: "This is a API service for Dompetly Finances App"
    info-contact-email: lukmann.dev@gmail.com
    info-contact-name: Dompetly Support
    info-license-name: Apache 2.0
    info-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  swagger-ui:
    enable: true
    always-include: true
  log:
    category:
      io.quarkus.security: DEBUG
      io.smallrye.jwt: DEBUG