quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://127.0.0.1:5432/${DB_NAME:dompetly_db}

mp:
  jwt:
    verify:
      publickey:
        location: /app/resources/jwt/publicKey.pem
      algorithm: RS256
    issuer: Dompetly App

smallrye:
  jwt:
    sign:
      key:
        location: /app/resources/jwt/privateKey.pem
      key-format: PEM
      algorithm: RS256
