quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:dompetly_db}

mp:
  jwt:
    verify:
      publickey:
        location: classpath:jwt/publicKey.pem
      algorithm: RS256
    issuer: Dompetly App

smallrye:
  jwt:
    sign:
      key:
        location: classpath:jwt/privateKey.pem
      key-format: PEM
      algorithm: RS256
