name: Deploy Quarkus App to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/project/dompetly_be
            
            echo "Pulling the latest code from the repository..."
            git pull origin main
            
            echo "Building the apps..."
            chmod +x ./mvnw
            ./mvnw clean package -Dquarkus.profile=prod
            
            echo "Restarting the service..."
            sudo -S /usr/bin/systemctl stop dompetly_be.service
            sudo -S /usr/bin/systemctl start dompetly_be.service
            echo "Deployment complete!"