name: Build and Deploy Quarkus App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Quarkus App
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests -Dquarkus.profile=prod

      - name: Copy build to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "target/quarkus-app/*"
          target: "/home/${{ secrets.VPS_USER }}/project/dompetly_api/target/quarkus-app/"
          strip_components: 2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            APP_PATH="/home/${{ secrets.VPS_USER }}/project/dompetly_api"
            JWT_PATH="$APP_PATH/src/main/resources/jwt"

            cd $APP_PATH

            echo "🔐 Generate JWT keys in correct format (PKCS#8)"
            mkdir -p $JWT_PATH
            if [ ! -f $JWT_PATH/privateKey.pem ]; then
              openssl genrsa -out $JWT_PATH/privateKey-pkcs1.pem 2048
              openssl pkcs8 -topk8 -inform PEM -outform PEM \
                -in $JWT_PATH/privateKey-pkcs1.pem -out $JWT_PATH/privateKey.pem -nocrypt
              rm $JWT_PATH/privateKey-pkcs1.pem
            fi
            if [ ! -f $JWT_PATH/publicKey.pem ]; then
              openssl rsa -in $JWT_PATH/privateKey.pem -pubout -out $JWT_PATH/publicKey.pem
            fi

            echo "Restarting service"
            sudo systemctl stop dompetly_api || true
            sudo systemctl start dompetly_api
            echo "Service restarted successfully"