name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Redeploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            APP_PATH="/home/${{ secrets.VPS_USER }}/project/dompetly_api"
            JWT_PATH="$APP_PATH/src/main/resources/jwt"
            cd $APP_PATH
            
            echo "Pulling latest changes from main branch"
            git stash  # Backup any local changes
            git pull origin main
            git stash pop || true  # Restore local changes if any

            echo "🔐 Generate JWT keys in correct format (PKCS#8)"
            mkdir -p $JWT_PATH
            if [ ! -f $JWT_PATH/privateKey.pem ]; then
              echo "➡️ Creating RSA key (PKCS#8)"
              openssl genrsa -out $JWT_PATH/privateKey-pkcs1.pem 2048
              openssl pkcs8 -topk8 -inform PEM -outform PEM \
                -in $JWT_PATH/privateKey-pkcs1.pem -out $JWT_PATH/privateKey.pem -nocrypt
              rm $JWT_PATH/privateKey-pkcs1.pem
            fi
            if [ ! -f $JWT_PATH/publicKey.pem ]; then
              echo "➡️ Extracting public key"
              openssl rsa -in $JWT_PATH/privateKey.pem -pubout -out $JWT_PATH/publicKey.pem
            fi
            
            echo "Building application"
            ./mvnw clean package -DskipTests -Dquarkus.profile=prod

            echo "Restarting service"
            sudo systemctl stop dompetly_api || true
            sudo systemctl start dompetly_api
            echo "Service restarted successfully"